Repository haanh764/surveyapp, pull requests merged in 2022-06, with the labels that each got.

#11 feat: finished my surveys, admin login view, fix: sidebar bugs
  ui/.eslintrc.js
  ui/src/App.vue
  ui/src/assets/json/lorem-ipsum.json
  ui/src/components/BottomSheet.vue
  ui/src/components/ContentCard.vue
  ui/src/components/ErrorMessage.vue
  ui/src/components/Links.vue
  ui/src/components/MaterialCard.vue
  ui/src/components/Modal.vue
  ui/src/filters/index.js
  ui/src/layouts/default/AppBar.vue
  ui/src/layouts/default/Drawer.vue
  ui/src/layouts/default/Footer.vue
  ui/src/layouts/default/Index.vue
  ui/src/layouts/default/List.vue
  ui/src/layouts/default/View.vue
  ui/src/layouts/default/widgets/DrawerHeader.vue
  ui/src/layouts/default/widgets/DrawerToggle.vue
  ui/src/main.js
  ui/src/router/index.js
  ui/src/store/modules/user.js
  ui/src/styles/components/_buttons.scss
  ui/src/styles/components/_typography.scss
  ui/src/styles/components/index.scss
  ui/src/styles/mixins/_buttons.scss
  ui/src/styles/variables/_colors.scss
  ui/src/util/dates.js
  ui/src/views/admin/login/LoginView.vue
  ui/src/views/general/landing/LandingView.vue
  ui/src/views/user/login-confirm/LoginConfirmView.vue
  ui/src/views/user/login/LoginView.vue
  ui/src/views/user/settings/SettingsView.vue
  ui/src/views/user/signup-thankyou/SignupThankyouView.vue
  ui/src/views/user/surveys/SurveysView.vue
  ui/src/views/user/surveys/components/ConditionsInteraction.vue
Labels: enhancement

#12 feat: finished 404 and SignupView, fixes: debugged error on SignupThankyouView
  ui/src/assets/svg/404.png
  ui/src/components/ContentCard.vue
  ui/src/views/PageNotFoundView.vue
  ui/src/views/user/signup-thankyou/SignupThankyouView.vue
  ui/src/views/user/signup/SignupView.vue
Labels: enhancement

#19 feat: finished ui pages UserSettings, UserDeleteThankyou, AdminSettings
  ui/src/components/Modal.vue
  ui/src/plugins/index.js
  ui/src/plugins/js-cookie.js
  ui/src/styles/variables.js
  ui/src/views/admin/settings/SettingsView.vue
  ui/src/views/user/delete-thankyou/DeleteThankyouView.vue
  ui/src/views/user/settings/SettingsView.vue
Labels: enhancement

#21 fix: changed foreign keys in tables answer_options_choice_answer, choice_answers
  db/create_db.sql
Labels: enhancement

#23 feat: finished ui pages admin-users, admin-surveys
  ui/src/router/index.js
  ui/src/store/modules/user.js
  ui/src/views/admin/login/LoginView.vue
  ui/src/views/admin/surveys/SurveysView.vue
  ui/src/views/admin/users/UsersView.vue
Labels: enhancement

#22 feat: finished form builder page
  ui/.eslintrc.js
  ui/package.json
  ui/src/App.vue
  ui/src/api/index.js
  ui/src/assets/json/form-builder-list-sample.json
  ui/src/components/BottomSheet.vue
  ui/src/components/ContentCard.vue
  ui/src/components/Modal.vue
  ui/src/components/ViewIntro.vue
  ui/src/form-builder/components/FormBuilder.vue
  ui/src/form-builder/components/GenerateForm.vue
  ui/src/form-builder/components/GenerateFormItem.vue
  ui/src/form-builder/components/WidgetConfig.vue
  ui/src/form-builder/components/WidgetForm.vue
  ui/src/form-builder/components/WidgetFormItem.vue
  ui/src/form-builder/components/components.js
  ui/src/form-builder/components/generateCode.js
  ui/src/form-builder/generator/constant.js
  ui/src/form-builder/generator/generateFormCode.js
  ui/src/form-builder/generator/generateFormItemCode.js
  ui/src/layouts/default/View.vue
  ui/src/layouts/default/widgets/Account.vue
  ui/src/layouts/default/widgets/AccountSettings.vue
  ui/src/layouts/default/widgets/GoHome.vue
  ui/src/layouts/default/widgets/Notifications.vue
  ui/src/layouts/default/widgets/Search.vue
  ui/src/mixins/index.js
  ui/src/mixins/notification.js
  ui/src/mixins/style.js
  ui/src/plugins/index.js
  ui/src/plugins/vuedraggable.js
  ui/src/plugins/vuetify-notify.js
  ui/src/styles/components/_buttons.scss
  ui/src/styles/mixins/_browser-variables.scss
  ui/src/styles/mixins/index.scss
  ui/src/styles/overrides.scss
  ui/src/styles/variables.js
  ui/src/styles/variables/_colors.scss
  ui/src/util/copy.js
  ui/src/util/event-bus.js
  ui/src/util/form-builder.js
  ui/src/views/admin/settings/SettingsView.vue
  ui/src/views/user/settings/SettingsView.vue
  ui/src/views/user/signup-thankyou/SignupThankyouView.vue
  ui/src/views/user/signup/SignupView.vue
  ui/src/views/user/survey-edit/SurveyEditView.vue
  ui/src/views/user/survey-edit/components/SurveyBuild.vue
  ui/src/views/user/survey-edit/components/SurveyConfigTabs.vue
  ui/src/views/user/survey-edit/components/SurveyEditTabs.vue
  ui/src/views/user/survey-edit/components/SurveyElements.vue
  ui/src/views/user/survey-edit/components/SurveyPreview.vue
  ui/src/views/user/survey-edit/components/SurveySettings.vue
  ui/src/views/user/surveys/SurveysView.vue
  ui/src/views/user/surveys/components/ConditionsInteraction.vue
  ui/vue.config.js
Labels: enhancement

#20 feat: Db connector implementation
  api/database/db_config.py
  api/database/db_connector.py
  api/models/admin.py
  api/models/question.py
  api/models/revoked_token.py
  api/models/survey.py
  api/models/user.py
  api/resources/admin.py
  api/resources/authentication.py
  api/resources/db_testing.py
  api/resources/routes.py
  api/resources/survey.py
  db/create_db.sql
Labels: documentation, enhancement

#27 feat: finished survey fill view page
  ui/.eslintrc.js
  ui/src/assets/json/survey-data-sample.json
  ui/src/components/ContentCard.vue
  ui/src/store/modules/user.js
  ui/src/util/dates.js
  ui/src/views/admin/surveys/SurveysView.vue
  ui/src/views/admin/users/UsersView.vue
  ui/src/views/general/survey-fill/SurveyFillView.vue
  ui/src/views/user/signup-thankyou/SignupThankyouView.vue
Labels: enhancement

#30 feat: implement API request for user-signup
  ui/.env.development
  ui/.env.production
  ui/src/api/index.js
  ui/src/views/user/signup/SignupView.vue
Labels: enhancement

#31 feat: finished the survey detail page, privacy policy, tnc
  ui/package.json
  ui/src/assets/json/survey-data-sample.json
  ui/src/components/BottomSheet.vue
  ui/src/components/ContentCard.vue
  ui/src/form-builder/components/GenerateForm.vue
  ui/src/form-builder/components/GenerateFormItem.vue
  ui/src/plugins/index.js
  ui/src/plugins/vue-friendly-iframe.js
  ui/src/styles/mixins/_typography.scss
  ui/src/styles/variables.js
  ui/src/util/dates.js
  ui/src/views/general/privacy-policy/PrivacyPolicyView.vue
  ui/src/views/general/survey-fill/SurveyFillView.vue
  ui/src/views/general/terms-and-conditions/TermsAndConditionsView.vue
  ui/src/views/user/signup-thankyou/SignupThankyouView.vue
  ui/src/views/user/survey-detail/SurveyDetailView.vue
  ui/src/views/user/survey-detail/components/DetailQuestions.vue
  ui/src/views/user/survey-detail/components/DetailResponses.vue
  ui/src/views/user/survey-detail/components/DetailSummary.vue
  ui/src/views/user/survey-edit/components/SurveyPreview.vue
  ui/src/views/user/survey-edit/components/SurveySettings.vue
Labels: enhancement

#34 feat: added cookies confirmation, standardized toast on api error
  ui/src/App.vue
  ui/src/api/index.js
  ui/src/components/BottomSheet.vue
  ui/src/layouts/default/CookiesConfirmation.vue
  ui/src/layouts/default/Footer.vue
  ui/src/router/index.js
  ui/src/store/index.js
  ui/src/store/modules/user.js
  ui/src/styles/overrides.scss
  ui/src/views/user/login/LoginView.vue
  ui/src/views/user/settings/SettingsView.vue
  ui/src/views/user/signup/SignupView.vue
  ui/src/views/user/surveys/SurveysView.vue
Labels: enhancement

#37 feat: implemented api calls user Login, user NotActivated, user ResendActivation
  ui/src/api/index.js
  ui/src/router/index.js
  ui/src/store/modules/user.js
  ui/src/views/user/login-confirm/LoginConfirmView.vue
  ui/src/views/user/login/LoginView.vue
  ui/src/views/user/signup-thankyou/SignupThankyouView.vue
Labels: enhancement

#39 feat: cypress installation, new example test file
  ui/README.md
  ui/cypress.config.js
  ui/package.json
  ui/src/api/index.js
  ui/src/components/BottomSheet.vue
  ui/src/layouts/default/Footer.vue
  ui/src/router/index.js
  ui/src/views/general/survey-submitted/SurveySubmittedView.vue
  ui/src/views/user/login/LoginView.vue
  ui/src/views/user/settings/SettingsView.vue
  ui/tests/e2e/.eslintrc.js
  ui/tests/e2e/plugins/index.js
  ui/tests/e2e/specs/general/landing/cookies-policy.cy.js
  ui/tests/e2e/specs/index.cy.js
  ui/tests/e2e/support/commands.js
  ui/tests/e2e/support/index.js
Labels: documentation, enhancement

#38 feat: API calls for user change pwd, delete acc, logout | fix: vue router mode to hash
  ui/src/api/index.js
  ui/src/router/index.js
  ui/src/views/user/settings/SettingsView.vue
Labels: enhancement

#43 fix: added eslint-plugin-cypress
  ui/package.json
Labels: enhancement

#45 feat: implemented API calls admin: login, logout, change pwd, user management actions
  ui/src/api/index.js
  ui/src/router/index.js
  ui/src/views/admin/login/LoginView.vue
  ui/src/views/admin/settings/SettingsView.vue
  ui/src/views/admin/users/UsersView.vue
Labels: enhancement

#47 feat: added user survey apis
  ui/.env.development
  ui/.env.production
  ui/src/api/config.js
  ui/src/api/index.js
  ui/src/util/dates.js
  ui/src/views/user/survey-detail/components/DetailResponses.vue
  ui/src/views/user/survey-detail/components/DetailSummary.vue
  ui/src/views/user/survey-edit/SurveyEditView.vue
  ui/src/views/user/surveys/SurveysView.vue
Labels: enhancement

#51 feat: added nav guard for unaccepted tnc pp
  ui/src/router/index.js
Labels: enhancement

#56 Finished connecting APIs
  README.md
  db/dump_mockup_data.sql
  ui/src/api/index.js
  ui/src/api/urls.js
  ui/src/assets/json/survey-data-sample.json
  ui/src/form-builder/components/FormBuilder.vue
  ui/src/views/admin/surveys/SurveysView.vue
  ui/src/views/general/survey-fill/SurveyFillView.vue
  ui/src/views/user/survey-detail/components/DetailQuestions.vue
  ui/src/views/user/survey-edit/SurveyEditView.vue
  ui/src/views/user/survey-edit/components/SurveyBuild.vue
  ui/src/views/user/survey-edit/components/SurveyConfigTabs.vue
  ui/src/views/user/survey-edit/components/SurveyEditTabs.vue
  ui/src/views/user/survey-edit/components/SurveySettings.vue
  ui/src/views/user/surveys/SurveysView.vue
Labels: enhancement, wontfix

#57 chore: updated README, cleaned the code
  README.md
  ui/src/api/index.js
  ui/src/views/general/survey-fill/SurveyFillView.vue
  ui/src/views/user/survey-detail/components/DetailResponses.vue
  ui/src/views/user/survey-edit/SurveyEditView.vue
  ui/src/views/user/survey-edit/components/SurveyBuild.vue
  ui/src/views/user/survey-edit/components/SurveyConfigTabs.vue
  ui/src/views/user/survey-edit/components/SurveySettings.vue
  ui/src/views/user/surveys/SurveysView.vue
  ui/tests/e2e/support/data/login-info.js
Labels: documentation

#58 feat: removed unused buttons, added tnc pp, added isBlocked check
  ui/src/api/index.js
  ui/src/api/urls.js
  ui/src/assets/json/pp.json
  ui/src/assets/json/tnc.json
  ui/src/router/index.js
  ui/src/store/modules/user.js
  ui/src/views/admin/login/LoginView.vue
  ui/src/views/general/privacy-policy/PrivacyPolicyView.vue
  ui/src/views/general/survey-fill/SurveyFillView.vue
  ui/src/views/general/terms-and-conditions/TermsAndConditionsView.vue
  ui/src/views/user/login-blocked/LoginBlockedView.vue
  ui/src/views/user/login/LoginView.vue
  ui/src/views/user/signup/SignupView.vue
  ui/src/views/user/survey-edit/SurveyEditView.vue
  ui/src/views/user/surveys/SurveysView.vue
Labels: enhancement

#61 fix: solved bugs with single choice question and opening response page
  api/resources/survey.py
  ui/src/views/general/survey-fill/SurveyFillView.vue
  ui/src/views/user/survey-detail/components/DetailQuestions.vue
  ui/src/views/user/survey-edit/SurveyEditView.vue
Labels: enhancement
